from playwright.sync_api import Page, expect

class PIMPage:

    def __init__(self, page: Page):
        self.page = page

        self.pim_menu = page.get_by_role("link", name="PIM")
        self.add_employee_button = page.get_by_role("button", name="Add")
        self.add_employee_heading = page.get_by_role("heading", name="Add Employee")
        self.first_name = page.get_by_placeholder("First Name")
        self.last_name = page.get_by_placeholder("Last Name")
        self.employee_id = page.locator("//label[text()='Employee Id']/../following-sibling::div/input")
        self.profile_picture = page.locator("input[type='file']")
        self.save_button = page.get_by_role("button", name="Save")
        self.employee_list_menu = page.get_by_role("link", name="Employee List")
        self.search_button = page.get_by_role("button", name="Search")
        self.employee_id_search = page.locator("//label[text()='Employee Id']/../following-sibling::div/input")
        self.employee_rows = page.locator(".oxd-table-body .oxd-table-row")
        self.job_tab = page.get_by_role("link", name="Job")
        self.job_title_dropdown = page.locator(".oxd-select-text").first
        self.employment_status_dropdown = page.locator(".oxd-select-text").last
        self.job_title=page.get_by_text("QA Engineer")
        self.employment_status=page.get_by_text("Full-Time Permanent")
        self.update_employee_details=page.get_by_role("button",name="Save")
        self.edit_button = page.locator("button:has(.bi-pencil-fill)")
        self.delete_button = page.locator("button:has(.bi-trash)")
        self.confirm_delete_button = page.get_by_role("button", name="Yes, Delete")
        self.no_records = self.page.locator("span.oxd-text--span:has-text('No Records Found')").first
        

    def open_add_employee_page(self):

        # Open PIM module
        self.pim_menu.click()

        # Open Add Employee page
        self.add_employee_button.click()

    def verify_add_employee_page_loaded(self):

        # Verify Add Employee page is displayed
        expect(self.add_employee_heading).to_be_visible()


    def add_employee(self, first_name, last_name, employee_id, profile_picture):
        self.first_name.fill(first_name)
        self.last_name.fill(last_name)

        # Replace autogenerated employee id
        self.employee_id.clear()
        self.employee_id.fill(employee_id)

        self.profile_picture.set_input_files(profile_picture)

        with self.page.expect_navigation():
            self.save_button.click()

        return employee_id
  
    def verify_employee_created(self):
        assert "viewPersonalDetails" in self.page.url, \
        f"Employee profile page not opened. Current URL: {self.page.url}"

    def open_employee_list(self):
        self.employee_list_menu.click()    

    def search_employee(self, employee_id):
        self.employee_id_search.fill(employee_id)
        self.search_button.click()    

    #Verify searched employee exists in results.
    def verify_employee_found(self, employee_id):
        expect(self.employee_rows.first).to_be_visible()
        # Verify employee exists
        employee_row = self.page.locator(f"div[role='row']:has-text('{employee_id}')")
        #employee_cell = self.page.locator(f"div[role='cell']:has-text('{employee_id}')")
        expect(employee_row).to_be_visible()

    def open_employee_record(self):
        with self.page.expect_navigation():
            self.edit_button.click() 

    def verify_employee_profile_opened(self):
        assert "viewPersonalDetails" in self.page.url, \
        f"Employee profile page not opened. Current URL: {self.page.url}"

    def open_job_tab(self):
        with self.page.expect_navigation():
            self.job_tab.click()  

    def verify_employee_job_tab_opened(self):
        assert "viewJobDetails" in self.page.url, \
        f"Job Details page not opened. Current URL: {self.page.url}" 

    def update_job_details(self):

        # Job Title
        self.job_title_dropdown.click()
        self.job_title.click()

        # Employment Status
        self.employment_status_dropdown.click()
        self.employment_status.click()    

        #click save
        self.update_employee_details.click()

        return "QA Engineer", "Full-Time Permanent"

    def verify_job_details_updated(self,job_title,employment_status):

        expect(self.page.get_by_text(job_title)).to_be_visible()
        expect(self.page.get_by_text(employment_status)).to_be_visible()    


    def delete_employee(self):
        self.delete_button.click()
        self.confirm_delete_button.click()

    def verify_employee_deleted(self, employee_id):
        self.search_employee(employee_id)
        # Look for "No Records Found"
        expect(self.no_records).to_be_visible()    


       


           